package mrs.domain.model.mybatis;

import java.io.Serializable;
import java.time.LocalDate;

public class ReservableRoomKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservable_room.reserved_date
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    private LocalDate reservedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reservable_room.room_id
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservable_room.reserved_date
     *
     * @return the value of public.reservable_room.reserved_date
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    public LocalDate getReservedDate() {
        return reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservable_room.reserved_date
     *
     * @param reservedDate the value for public.reservable_room.reserved_date
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    public void setReservedDate(LocalDate reservedDate) {
        this.reservedDate = reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reservable_room.room_id
     *
     * @return the value of public.reservable_room.room_id
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reservable_room.room_id
     *
     * @param roomId the value for public.reservable_room.room_id
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
}