package mrs.domain.mapper.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import mrs.domain.model.mybatis.MeetingRoom;
import mrs.domain.model.mybatis.MeetingRoomExample;

@Mapper
public interface MeetingRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    long countByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int deleteByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int deleteByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int insert(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int insertSelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    List<MeetingRoom> selectByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    MeetingRoom selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByExampleSelective(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByExample(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByPrimaryKeySelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.meeting_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByPrimaryKey(MeetingRoom record);
}