package mrs.domain.mapper.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import mrs.domain.model.mybatis.ReservableRoomExample;
import mrs.domain.model.mybatis.ReservableRoomKey;

@Mapper
public interface ReservableRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    long countByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int deleteByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int deleteByPrimaryKey(ReservableRoomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int insert(ReservableRoomKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int insertSelective(ReservableRoomKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    List<ReservableRoomKey> selectByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByExampleSelective(@Param("record") ReservableRoomKey record, @Param("example") ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reservable_room
     *
     * @mbg.generated Sun Jun 07 22:31:33 JST 2020
     */
    int updateByExample(@Param("record") ReservableRoomKey record, @Param("example") ReservableRoomExample example);
}