package mrs.domain.mapper.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import mrs.domain.model.mybatis.Usr;
import mrs.domain.model.mybatis.UsrExample;

@Mapper
public interface UsrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	long countByExample(UsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int deleteByExample(UsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int insert(Usr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int insertSelective(Usr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	List<Usr> selectByExample(UsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	Usr selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int updateByExampleSelective(@Param("record") Usr record, @Param("example") UsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int updateByExample(@Param("record") Usr record, @Param("example") UsrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int updateByPrimaryKeySelective(Usr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usr
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	int updateByPrimaryKey(Usr record);
}